### ISSUE TITLE
OS error 2

### ISSUE THREAD

**Issue by Sektora** [valentinegb/bonelab_mod_manager#16]
Im getting os error 2 cause i had to remove all the mods it installed and resubcribe to mods I actually wanted,
now it just says : The system cannot find the file specified. (os error 2)
what should I do?
![image_2023-10-03_182506135](https://github.com/valentinegb/bonelab_mod_manager/assets/146676983/1ce5773d-9868-418a-9244-91ed331cbe4b)

**Comment by valentinegb** [comment]
When you run it, it checks if you've unsubscribed to a mod and it will uninstall it for you, so what's probably happening here is it sees that you've unsubscribed to a mod, it sees that the mod is reportedly still installed (even though you manually uninstalled it, it stores a list of installed mods in the `app_data` file), and so it tries to delete the folder, which doesn't exist.

Unfortunately, **to fix this** you'll need to delete all of the app data for the mod manager, which means deleting the entire `com.valentinegb.bonelab_mod_manager` folder. In the future, just let the mod manager uninstall your mods for you!

I think I might also make an update so that if this ever happens again, it'll automatically reset the app data.

**Comment by Sektora** [comment]
where is the app data location
I mean like where would I delete it all if the app data is gone

**Comment by valentinegb** [comment]
The directory you should delete is `%AppData%/bonelab_mod_manager`, then the next time you run the mod manager it will recreate the directory with functioning app data.

**Comment by Sektora** [comment]
Will do, thank you so much!

**Comment by valentinegb** [comment]
Sorry, I said `com.valentinegb.bonelab_mod_manager` earlier but it's only called that in Mac and Linux!
