### ISSUE TITLE
Is there a way to reset the mod manager? 

### ISSUE THREAD

**Issue by beanie-3** [valentinegb/bonelab_mod_manager#29]
Apologies that im back with another issue but after uninstallation of all bonelab mods, the manager only reinstalled about half of my subscribed mods. On the manager it does say that the mods that are already installed, yet the mods are not. I did think of unsubscribing to a mod and resubscribing to mods but that did not work. Some help would be appreciated

**Comment by valentinegb** [comment]
Yes, you can reset the mod manager by deleting the `%AppData%/bonelab_mod_manager` folder. You should be able to copy-paste that into the path text-field in File Explorer and it should take you right to it.

Your issue probably came about because there is no system in place to actually verify if a mod is installed, but there is one to make sure it's actually uninstalled. That sounds like something I'll probably add pretty soon lol

**Comment by beanie-3** [comment]
alrighty! I'll let you know if it works!

**Comment by beanie-3** [comment]
It worked! Thank you so much once again!
