### ISSUE TITLE
Mod manager flatout breaking

### ISSUE THREAD

**Issue by bobo34213** [valentinegb/bonelab_mod_manager#30]
For some reason I've downloaded and deleted a few mods and for some reason when I open it, it just shows: 
![why](https://github.com/valentinegb/bonelab_mod_manager/assets/152114054/47345d87-2455-465d-ae0a-89961baeecb5)

Occasionally, it just shows nothing, so how can I fix this?

**Comment by valentinegb** [comment]
Enable debug features according to this comment: https://github.com/valentinegb/bonelab_mod_manager/issues/28#issuecomment-1822030524
Then let me know what the output is and I'll help pinpoint the mod that's causing issues.

**Comment by bobo34213** [comment]
after doing what you said, it shows the following:
![debug1](https://github.com/valentinegb/bonelab_mod_manager/assets/152114054/de357dba-b4a2-4a63-9484-9de96dca82dd)
![debug2](https://github.com/valentinegb/bonelab_mod_manager/assets/152114054/69c93979-8242-4e41-83e9-e98fa41d158a)

**Comment by valentinegb** [comment]
It appears to be attempting to remove this mod: https://mod.io/g/bonelab/m/dev-save-patch-3
It's failing because this mod kind of isn't really a mod, in any case it's not meant to be put into the `Mods` folder. You'll have to find  and remove the files associated with this "mod" for the mod manager to work properly again. I suggest starting with removing the `slot_0.save.json` file.

**Comment by bobo34213** [comment]
so i've directly deleted all "save" mods both directly from the files and from mod.io, though it still shows the same thing.

**Comment by bobo34213** [comment]
nevermind, there was a random slotsave.json file that i forgot to delete because it was extracted for some reason?? it works now.
