### ISSUE TITLE
os error 267 (windows 11)

### ISSUE THREAD

**Issue by hortenhonuke** [valentinegb/bonelab_mod_manager#35]
I'm on windows 11 and I know a couple of people have had the same issue and where told to setup an environment variable. I tried to follow the guide that was linked and in the process of setting it up I just got a errors, not form the manager but trying to setup the environment variable, which could be due to my own stupidity and not knowing how this stuff works. I have tried looking for a step by step video on how to do this but couldn't find one.

**Comment by valentinegb** [comment]
If you can't get the environment variable working you can also download a debug build and it'll have the debug info by default. You can get that from here: https://github.com/valentinegb/bonelab_mod_manager/actions/runs/7316307515

**Comment by hortenhonuke** [comment]
opened the debug and i got this.

![Screenshot 2023-12-27 204232](https://github.com/valentinegb/bonelab-mod-manager/assets/154730716/b7a52713-427f-417f-8578-b06050630be6)

**Comment by valentinegb** [comment]
This is the installed mod that's causing issues: https://mod.io/g/bonelab/m/terminator-resistances-t-800
It's causing issues because the author of the mod is distributing the changelog in a TXT file, which is not standard practice and isn't handled by the mod manager. You must find the files that originate from this mod in your `Mods` folder and remove them manually.

**Comment by hortenhonuke** [comment]
The files took a bit to find but removing the mod fixed the problem and now runs perfectly fine now, thanks for the help.
